# Experiment 7: training episode size — results

Compare 2,048, 8,192 and 26,000 total training rows on one fixed large-table pool. The 8,192-row control is reused explicitly from experiment 6. Context and query size both increase; update budgets, not compute or row exposures, are matched.

## 0. Evidence and scope

In [1]:
%matplotlib inline
import sys
from pathlib import Path
REPO = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / 'pyproject.toml').is_file())
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))
from src.visualize import style, campaign as cp, size_studies as ss
from src.visualize.figures import FigureSaver
from src.visualize.inputs import source_description
style.apply()
sink = FigureSaver('experiment7/02_results')
report = cp.NotebookReport('Experiment 7: training episode size — results', sink=sink)
print(source_description())
arms = ss.load_arms(7)
report.add('0. Evidence and scope', source_description() + '\n' + 'Compare 2,048, 8,192 and 26,000 total training rows on one fixed large-table pool. The 8,192-row control is reused explicitly from experiment 6. Context and query size both increase; update budgets, not compute or row exposures, are matched.')

DATA: output CreditPFN.zip; modified 2026-10-13T12:13:29+00:00; read only.
Project: output CreditPFN; modified 2026-10-13T14:04:38+00:00; read only.
Missing project records are unavailable evidence, not zero effects or failed training.

## 1. Coverage and the fixed evaluation population

In [2]:
report.table('Planned and recorded evidence', ss.coverage(arms))
report.table('Prepared corpus and exposure inventory', ss.corpus_inventory(arms))
report.add('1. Coverage and the fixed evaluation population', 'Missing records are unavailable evidence. PENDING is not a live scheduler state. The four original dataset partitions and five row-level evaluation folds remain fixed. Shared controls count once.')

,arm,source_experiment,source_run,planned,completed,other_outcomes,pending,trajectory_records,benchmark_fold_records
0,"2,048 rows",experiment7,cpt_episode_rows2048_v1,8,0,0,8,0,0
1,"8,192 rows",experiment6,cpt_corpus_v1,8,0,0,8,0,0
2,"26,000 rows",experiment7,cpt_episode_rows26000_v1,8,0,0,8,0,0

Empty DataFrame
Columns: []
Index: []

## 2. Paired AUC effects and study contrasts

In [3]:
cp.show(sink, ss.plot_benchmark(arms))
report.add('2. Paired AUC effects and study contrasts', 'Report all prescribed arms. Each table is paired across arms and its original-weight control, requiring complete five-fold evaluation. Partitions and CV folds are not independent replications.')

No measurements available for this section yet.

## 3. Probability quality

In [4]:
cp.show(sink, ss.plot_benchmark(arms, 'brier_score'))
report.add('3. Probability quality', 'Positive Brier effects mean a reduction in error. These are secondary outcomes at natural test prevalence; do not select an arm with them.')

No measurements available for this section yet.

## 4. Interpretation

In [5]:
report.table('Completed and unavailable comparisons', ss.coverage(arms))
report.add('4. Interpretation', 'Compare 2,048, 8,192 and 26,000 total training rows on one fixed large-table pool. The 8,192-row control is reused explicitly from experiment 6. Context and query size both increase; update budgets, not compute or row exposures, are matched. Differences are descriptive for this credit corpus, horizon and two base architectures. These studies do not estimate a corpus-by-episode interaction or an effect of dataset size independent of population identity.')

,arm,source_experiment,source_run,planned,completed,other_outcomes,pending,trajectory_records,benchmark_fold_records
0,"2,048 rows",experiment7,cpt_episode_rows2048_v1,8,0,0,8,0,0
1,"8,192 rows",experiment6,cpt_corpus_v1,8,0,0,8,0,0
2,"26,000 rows",experiment7,cpt_episode_rows26000_v1,8,0,0,8,0,0

## Complete text summary

In [6]:
print(report.summary(sink))

Experiment 7: training episode size — results

0. Evidence and scope
DATA: output CreditPFN.zip; modified 2026-10-13T12:13:29+00:00; read only.
Project: output CreditPFN; modified 2026-10-13T14:04:38+00:00; read only.
Missing project records are unavailable evidence, not zero effects or failed training.
Compare 2,048, 8,192 and 26,000 total training rows on one fixed large-table pool. The 8,192-row control is reused explicitly from experiment 6. Context and query size both increase; update budgets, not compute or row exposures, are matched.

1. Coverage and the fixed evaluation population
Missing records are unavailable evidence. PENDING is not a live scheduler state. The four original dataset partitions and five row-level evaluation folds remain fixed. Shared controls count once.

Table: Planned and recorded evidence
CSV (first column: row index)
row,arm,source_experiment,source_run,planned,completed,other_outcomes,pending,trajectory_records,benchmark_fold_records
0,"2,048 rows",experiment7,cpt_episode_rows2048_v1,8,0,0,8,0,0
1,"8,192 rows",experiment6,cpt_corpus_v1,8,0,0,8,0,0
2,"26,000 rows",experiment7,cpt_episode_rows26000_v1,8,0,0,8,0,0

Table: Prepared corpus and exposure inventory
CSV (first column: row index)
row

2. Paired AUC effects and study contrasts
Report all prescribed arms. Each table is paired across arms and its original-weight control, requiring complete five-fold evaluation. Partitions and CV folds are not independent replications.

No measurements available for this figure group.

3. Probability quality
Positive Brier effects mean a reduction in error. These are secondary outcomes at natural test prevalence; do not select an arm with them.

No measurements available for this figure group.

4. Interpretation
Compare 2,048, 8,192 and 26,000 total training rows on one fixed large-table pool. The 8,192-row control is reused explicitly from experiment 6. Context and query size both increase; update budgets, not compute or row exposures, are matched. Differences are descriptive for this credit corpus, horizon and two base architectures. These studies do not estimate a corpus-by-episode interaction or an effect of dataset size independent of population identity.

Table: Completed and unavailable comparisons
CSV (first column: row index)
row,arm,source_experiment,source_run,planned,completed,other_outcomes,pending,trajectory_records,benchmark_fold_records
0,"2,048 rows",experiment7,cpt_episode_rows2048_v1,8,0,0,8,0,0
1,"8,192 rows",experiment6,cpt_corpus_v1,8,0,0,8,0,0
2,"26,000 rows",experiment7,cpt_episode_rows26000_v1,8,0,0,8,0,0

experiment7/02_results: no figures saved.