# Experiment 7: training episode size — results

Compare 2,048, 8,192 and 26,000 total training rows on one fixed large-table pool. The 8,192-row control is reused explicitly from experiment 6. Context and query size both increase; update budgets, not compute or row exposures, are matched.

Does a longer training episode improve credit transfer within the same large-table corpus? Both context and query rows increase; updates are matched, compute is not.

## 0. Evidence and scope

In [1]:
%matplotlib inline
import sys
from pathlib import Path
REPO = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / 'pyproject.toml').is_file())
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))
from src.visualize import style, campaign as cp, size_studies as ss
from src.visualize.figures import FigureSaver
from src.visualize.inputs import source_description
style.apply()
sink = FigureSaver('experiment7/02_results')
report = cp.NotebookReport('Experiment 7: training episode size — results', sink=sink)
print(source_description())
arms = ss.load_arms(7)
report.add('0. Evidence and scope', source_description() + '\n' + 'Compare 2,048, 8,192 and 26,000 total training rows on one fixed large-table pool. The 8,192-row control is reused explicitly from experiment 6. Context and query size both increase; update budgets, not compute or row exposures, are matched.')
from src.visualize import prediction_diagnostics as pred

DATA: output CreditPFN.zip; modified 2026-10-16T07:14:04+00:00; read only.
Project: output CreditPFN; modified 2026-10-16T08:49:22+00:00; read only.
Missing project records are unavailable evidence, not zero effects or failed training.

## 1. Coverage and the fixed evaluation population

In [2]:
report.table('Planned and recorded evidence', ss.coverage(arms))
report.table('Prepared corpus and exposure inventory', ss.corpus_inventory(arms))
report.add('1. Coverage and the fixed evaluation population', 'Missing records are unavailable evidence. PENDING is not a live scheduler state. The four original dataset partitions and five row-level evaluation folds remain fixed. Shared controls count once.')

,arm,source_experiment,source_run,planned,completed,other_outcomes,pending,trajectory_records,benchmark_fold_records
0,"2,048 rows",experiment7,cpt_episode_rows2048_v1,8,8,0,0,24,0
1,"8,192 rows",experiment6,cpt_corpus_v1,8,8,0,0,18,0
2,"26,000 rows",experiment7,cpt_episode_rows26000_v1,8,8,0,0,12,0

,arm,partition,id,available_rows,episode_rows,query_rows,visit_share,held_out_tables
0,"2,048 rows",0,0001.gmsc,150000,2048,819,0.111111,4
1,"2,048 rows",0,0002.taiwan_creditcard,30000,2048,819,0.111111,4
2,"2,048 rows",0,0003.vehicle_loan,233154,2048,819,0.111111,4
3,"2,048 rows",0,0006.hackerearth,532428,2048,819,0.111111,4
4,"2,048 rows",0,0007.cobranded,80000,2048,819,0.111111,4
...,...,...,...,...,...,...,...,...
94,"26,000 rows",3,PropPD1,100000,26000,10400,0.111111,4
95,"26,000 rows",3,PropPD2,105471,26000,10400,0.111111,4
96,"26,000 rows",3,0014.algorithmwatch,158700,26000,10400,0.111111,4
97,"26,000 rows",3,0015.credit_risk_dataset,32581,26000,10400,0.111111,4
98,"26,000 rows",3,0016.bondora_peer2peer,730176,26000,10400,0.111111,4

## 2. Paired AUC effects and study contrasts

In [3]:
cp.show(sink, ss.plot_benchmark(arms))
report.add('2. Paired AUC effects and study contrasts', 'Report all prescribed arms. Each table is paired across arms and its original-weight control, requiring complete five-fold evaluation. Partitions and CV folds are not independent replications.')

No measurements available for this section yet.

## 3. Probability quality

Saved raw test predictions additionally measure systematic over/underprediction and paired prediction changes. These diagnostics describe observed errors; they do not identify theoretical bias or context variance.

In [4]:
cp.show(sink, ss.plot_benchmark(arms, 'brier_score'))
prediction_tables, coverage_tables = [], []
for arm, run in arms.items():
    values, coverage = pred.analyze(run, arm=arm)
    prediction_tables.append(values)
    coverage_tables.append(coverage)
    report.table(arm+' saved prediction coverage', coverage)
    report.table(arm+' paired per-table prediction diagnostics', values)
cp.show(sink, pred.plot_arms(prediction_tables, coverage_tables, 'pd'))
report.add('3. Probability quality', 'Positive Brier effects mean a reduction in error. These are secondary outcomes at natural test prevalence; do not select an arm with them.' + '\n' + pred.NOTE)

No measurements available for this section yet.

        status                reason
0  unavailable  No benchmark records

Empty DataFrame
Columns: []
Index: []

        status                reason
0  unavailable  No benchmark records

Empty DataFrame
Columns: []
Index: []

        status                reason
0  unavailable  No benchmark records

Empty DataFrame
Columns: []
Index: []

No measurements available for this section yet.

## 4. Interpretation

In [5]:
report.table('Completed and unavailable comparisons', ss.coverage(arms))
report.add('4. Interpretation', 'Compare 2,048, 8,192 and 26,000 total training rows on one fixed large-table pool. The 8,192-row control is reused explicitly from experiment 6. Context and query size both increase; update budgets, not compute or row exposures, are matched. Differences are descriptive for this credit corpus, horizon and two base architectures. These studies do not estimate a corpus-by-episode interaction or an effect of dataset size independent of population identity.')

,arm,source_experiment,source_run,planned,completed,other_outcomes,pending,trajectory_records,benchmark_fold_records
0,"2,048 rows",experiment7,cpt_episode_rows2048_v1,8,8,0,0,24,0
1,"8,192 rows",experiment6,cpt_corpus_v1,8,8,0,0,18,0
2,"26,000 rows",experiment7,cpt_episode_rows26000_v1,8,8,0,0,12,0

## Complete text summary

In [6]:
print(report.summary(sink))

Experiment 7: training episode size — results

0. Evidence and scope
DATA: output CreditPFN.zip; modified 2026-10-16T07:14:04+00:00; read only.
Project: output CreditPFN; modified 2026-10-16T08:49:22+00:00; read only.
Missing project records are unavailable evidence, not zero effects or failed training.
Compare 2,048, 8,192 and 26,000 total training rows on one fixed large-table pool. The 8,192-row control is reused explicitly from experiment 6. Context and query size both increase; update budgets, not compute or row exposures, are matched.

1. Coverage and the fixed evaluation population
Missing records are unavailable evidence. PENDING is not a live scheduler state. The four original dataset partitions and five row-level evaluation folds remain fixed. Shared controls count once.

Table: Planned and recorded evidence
CSV (first column: row index)
row,arm,source_experiment,source_run,planned,completed,other_outcomes,pending,trajectory_records,benchmark_fold_records
0,"2,048 rows",experiment7,cpt_episode_rows2048_v1,8,8,0,0,24,0
1,"8,192 rows",experiment6,cpt_corpus_v1,8,8,0,0,18,0
2,"26,000 rows",experiment7,cpt_episode_rows26000_v1,8,8,0,0,12,0

Table: Prepared corpus and exposure inventory
CSV (first column: row index)
row,arm,partition,id,available_rows,episode_rows,query_rows,visit_share,held_out_tables
0,"2,048 rows",0,0001.gmsc,150000,2048,819,0.11111111,4
1,"2,048 rows",0,0002.taiwan_creditcard,30000,2048,819,0.11111111,4
2,"2,048 rows",0,0003.vehicle_loan,233154,2048,819,0.11111111,4
3,"2,048 rows",0,0006.hackerearth,532428,2048,819,0.11111111,4
4,"2,048 rows",0,0007.cobranded,80000,2048,819,0.11111111,4
5,"2,048 rows",0,PropPD1,100000,2048,819,0.11111111,4
6,"2,048 rows",0,PropPD2,105471,2048,819,0.11111111,4
7,"2,048 rows",0,0012.home_credit,307511,2048,819,0.11111111,4
8,"2,048 rows",0,0015.credit_risk_dataset,32581,2048,819,0.11111111,4
9,"2,048 rows",1,0006.hackerearth,532428,2048,819,0.125,4
10,"2,048 rows",1,0007.cobranded,80000,2048,819,0.125,4
11,"2,048 rows",1,PropPD1,100000,2048,819,0.125,4
12,"2,048 rows",1,PropPD2,105471,2048,819,0.125,4
13,"2,048 rows",1,0012.home_credit,307511,2048,819,0.125,4
14,"2,048 rows",1,0014.algorithmwatch,158700,2048,819,0.125,4
15,"2,048 rows",1,0015.credit_risk_dataset,32581,2048,819,0.125,4
16,"2,048 rows",1,0016.bondora_peer2peer,730176,2048,819,0.125,4
17,"2,048 rows",2,0001.gmsc,150000,2048,819,0.14285714,5
18,"2,048 rows",2,0002.taiwan_creditcard,30000,2048,819,0.14285714,5
19,"2,048 rows",2,0003.vehicle_loan,233154,2048,819,0.14285714,5
20,"2,048 rows",2,0007.cobranded,80000,2048,819,0.14285714,5
21,"2,048 rows",2,0012.home_credit,307511,2048,819,0.14285714,5
22,"2,048 rows",2,0014.algorithmwatch,158700,2048,819,0.14285714,5
23,"2,048 rows",2,0016.bondora_peer2peer,730176,2048,819,0.14285714,5
24,"2,048 rows",3,0001.gmsc,150000,2048,819,0.11111111,4
25,"2,048 rows",3,0002.taiwan_creditcard,30000,2048,819,0.11111111,4
26,"2,048 rows",3,0003.vehicle_loan,233154,2048,819,0.11111111,4
27,"2,048 rows",3,0006.hackerearth,532428,2048,819,0.11111111,4
28,"2,048 rows",3,PropPD1,100000,2048,819,0.11111111,4
29,"2,048 rows",3,PropPD2,105471,2048,819,0.11111111,4
30,"2,048 rows",3,0014.algorithmwatch,158700,2048,819,0.11111111,4
31,"2,048 rows",3,0015.credit_risk_dataset,32581,2048,819,0.11111111,4
32,"2,048 rows",3,0016.bondora_peer2peer,730176,2048,819,0.11111111,4
33,"8,192 rows",0,0001.gmsc,150000,8192,3277,0.11111111,4
34,"8,192 rows",0,0002.taiwan_creditcard,30000,8192,3277,0.11111111,4
35,"8,192 rows",0,0003.vehicle_loan,233154,8192,3277,0.11111111,4
36,"8,192 rows",0,0006.hackerearth,532428,8192,3277,0.11111111,4
37,"8,192 rows",0,0007.cobranded,80000,8192,3277,0.11111111,4
38,"8,192 rows",0,PropPD1,100000,8192,3277,0.11111111,4
39,"8,192 rows",0,PropPD2,105471,8192,3277,0.11111111,4
40,"8,192 rows",0,0012.home_credit,307511,8192,3277,0.11111111,4
41,"8,192 rows",0,0015.credit_risk_dataset,32581,8192,3277,0.11111111,4
42,"8,192 rows",1,0006.hackerearth,532428,8192,3277,0.125,4
43,"8,192 rows",1,0007.cobranded,80000,8192,3277,0.125,4
44,"8,192 rows",1,PropPD1,100000,8192,3277,0.125,4
45,"8,192 rows",1,PropPD2,105471,8192,3277,0.125,4
46,"8,192 rows",1,0012.home_credit,307511,8192,3277,0.125,4
47,"8,192 rows",1,0014.algorithmwatch,158700,8192,3277,0.125,4
48,"8,192 rows",1,0015.credit_risk_dataset,32581,8192,3277,0.125,4
49,"8,192 rows",1,0016.bondora_peer2peer,730176,8192,3277,0.125,4
50,"8,192 rows",2,0001.gmsc,150000,8192,3277,0.14285714,5
51,"8,192 rows",2,0002.taiwan_creditcard,30000,8192,3277,0.14285714,5
52,"8,192 rows",2,0003.vehicle_loan,233154,8192,3277,0.14285714,5
53,"8,192 rows",2,0007.cobranded,80000,8192,3277,0.14285714,5
54,"8,192 rows",2,0012.home_credit,307511,8192,3277,0.14285714,5
55,"8,192 rows",2,0014.algorithmwatch,158700,8192,3277,0.14285714,5
56,"8,192 rows",2,0016.bondora_peer2peer,730176,8192,3277,0.14285714,5
57,"8,192 rows",3,0001.gmsc,150000,8192,3277,0.11111111,4
58,"8,192 rows",3,0002.taiwan_creditcard,30000,8192,3277,0.11111111,4
59,"8,192 rows",3,0003.vehicle_loan,233154,8192,3277,0.11111111,4
60,"8,192 rows",3,0006.hackerearth,532428,8192,3277,0.11111111,4
61,"8,192 rows",3,PropPD1,100000,8192,3277,0.11111111,4
62,"8,192 rows",3,PropPD2,105471,8192,3277,0.11111111,4
63,"8,192 rows",3,0014.algorithmwatch,158700,8192,3277,0.11111111,4
64,"8,192 rows",3,0015.credit_risk_dataset,32581,8192,3277,0.11111111,4
65,"8,192 rows",3,0016.bondora_peer2peer,730176,8192,3277,0.11111111,4
66,"26,000 rows",0,0001.gmsc,150000,26000,10400,0.11111111,4
67,"26,000 rows",0,0002.taiwan_creditcard,30000,26000,10400,0.11111111,4
68,"26,000 rows",0,0003.vehicle_loan,233154,26000,10400,0.11111111,4
69,"26,000 rows",0,0006.hackerearth,532428,26000,10400,0.11111111,4
70,"26,000 rows",0,0007.cobranded,80000,26000,10400,0.11111111,4
71,"26,000 rows",0,PropPD1,100000,26000,10400,0.11111111,4
72,"26,000 rows",0,PropPD2,105471,26000,10400,0.11111111,4
73,"26,000 rows",0,0012.home_credit,307511,26000,10400,0.11111111,4
74,"26,000 rows",0,0015.credit_risk_dataset,32581,26000,10400,0.11111111,4
75,"26,000 rows",1,0006.hackerearth,532428,26000,10400,0.125,4
76,"26,000 rows",1,0007.cobranded,80000,26000,10400,0.125,4
77,"26,000 rows",1,PropPD1,100000,26000,10400,0.125,4
78,"26,000 rows",1,PropPD2,105471,26000,10400,0.125,4
79,"26,000 rows",1,0012.home_credit,307511,26000,10400,0.125,4
80,"26,000 rows",1,0014.algorithmwatch,158700,26000,10400,0.125,4
81,"26,000 rows",1,0015.credit_risk_dataset,32581,26000,10400,0.125,4
82,"26,000 rows",1,0016.bondora_peer2peer,730176,26000,10400,0.125,4
83,"26,000 rows",2,0001.gmsc,150000,26000,10400,0.14285714,5
84,"26,000 rows",2,0002.taiwan_creditcard,30000,26000,10400,0.14285714,5
85,"26,000 rows",2,0003.vehicle_loan,233154,26000,10400,0.14285714,5
86,"26,000 rows",2,0007.cobranded,80000,26000,10400,0.14285714,5
87,"26,000 rows",2,0012.home_credit,307511,26000,10400,0.14285714,5
88,"26,000 rows",2,0014.algorithmwatch,158700,26000,10400,0.14285714,5
89,"26,000 rows",2,0016.bondora_peer2peer,730176,26000,10400,0.14285714,5
90,"26,000 rows",3,0001.gmsc,150000,26000,10400,0.11111111,4
91,"26,000 rows",3,0002.taiwan_creditcard,30000,26000,10400,0.11111111,4
92,"26,000 rows",3,0003.vehicle_loan,233154,26000,10400,0.11111111,4
93,"26,000 rows",3,0006.hackerearth,532428,26000,10400,0.11111111,4
94,"26,000 rows",3,PropPD1,100000,26000,10400,0.11111111,4
95,"26,000 rows",3,PropPD2,105471,26000,10400,0.11111111,4
96,"26,000 rows",3,0014.algorithmwatch,158700,26000,10400,0.11111111,4
97,"26,000 rows",3,0015.credit_risk_dataset,32581,26000,10400,0.11111111,4
98,"26,000 rows",3,0016.bondora_peer2peer,730176,26000,10400,0.11111111,4

2. Paired AUC effects and study contrasts
Report all prescribed arms. Each table is paired across arms and its original-weight control, requiring complete five-fold evaluation. Partitions and CV folds are not independent replications.

No measurements available for this figure group.

3. Probability quality
Positive Brier effects mean a reduction in error. These are secondary outcomes at natural test prevalence; do not select an arm with them.
Raw predictions are paired by dataset, training partition, outer fold and row. All five folds and exactly matching test rows/targets are required. Mean error is prediction minus observed target: positive means overprediction. Its absolute value can conceal offsetting subgroup errors. Brier/MSE and prediction movement pool rows within each table; tables receive equal weight in summaries. These are observed out-of-fold diagnostics, not squared theoretical bias or context variance.

No measurements available for this figure group.

Table: 2,048 rows saved prediction coverage
CSV (first column: row index)
row,status,reason
0,unavailable,No benchmark records

Table: 2,048 rows paired per-table prediction diagnostics
CSV (first column: row index)
row

Table: 8,192 rows saved prediction coverage
CSV (first column: row index)
row,status,reason
0,unavailable,No benchmark records

Table: 8,192 rows paired per-table prediction diagnostics
CSV (first column: row index)
row

Table: 26,000 rows saved prediction coverage
CSV (first column: row index)
row,status,reason
0,unavailable,No benchmark records

Table: 26,000 rows paired per-table prediction diagnostics
CSV (first column: row index)
row

No measurements available for this figure group.

4. Interpretation
Compare 2,048, 8,192 and 26,000 total training rows on one fixed large-table pool. The 8,192-row control is reused explicitly from experiment 6. Context and query size both increase; update budgets, not compute or row exposures, are matched. Differences are descriptive for this credit corpus, horizon and two base architectures. These studies do not estimate a corpus-by-episode interaction or an effect of dataset size independent of population identity.

Table: Completed and unavailable comparisons
CSV (first column: row index)
row,arm,source_experiment,source_run,planned,completed,other_outcomes,pending,trajectory_records,benchmark_fold_records
0,"2,048 rows",experiment7,cpt_episode_rows2048_v1,8,8,0,0,24,0
1,"8,192 rows",experiment6,cpt_corpus_v1,8,8,0,0,18,0
2,"26,000 rows",experiment7,cpt_episode_rows26000_v1,8,8,0,0,12,0

experiment7/02_results: no figures saved.