# Experiment 0: auxiliary experiment checks

Fast functional checks for experiments 2 and 3. These short runs verify seeds, disjoint sampling, averaged-gradient updates, checkpoint recovery and evaluation. They do not measure research performance or certify large-table memory limits.

## 0. Evidence and scope

In [1]:
%matplotlib inline
import sys
from pathlib import Path
REPO = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / 'pyproject.toml').is_file())
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))
from src.visualize import style, campaign as cp
from src.visualize.figures import FigureSaver
from src.visualize.inputs import source_description
style.apply()
sink = FigureSaver('experiment0/04_auxiliary_experiments')
report = cp.NotebookReport('Experiment 0: auxiliary experiment checks', sink=sink)

print(source_description())
report.add('0. Evidence and scope', source_description())
from src.visualize import auxiliary as aux

DATA: no external source selected.
Project: no external source selected.
Missing project records are unavailable evidence, not zero effects or failed training.

## 1. Planned checks

Eight GPU tasks cover TabPFN v2, TabPFN v2.6, TabPFN v3 and TabICL v2 on both tracks. Each task executes its short cases sequentially. Two small adaptation tables and one held-out table preserve their roles in dataset partition zero. TabICLv2 uses its own native objective. The fixed reference uses full updates, peak LR 3e-7 and L2-SP 0.003.

In [2]:
report.table('Planned auxiliary cases', aux.planned_checks())
report.add('1. Planned checks', '52 six-update arms across eight GPU tasks: 36 uninterrupted arms and 16 interrupted/resumed comparisons. LGD seed-42 one-sample also serves as the stratified sampling control. PD has a separate stratified control. The tiny 256-row cap and smoke retention panel bound debugging cost.')

,track,case,bases,updates,interrupt_after,row_cap,purpose
0,PD,seed42,4,6,NaN,256,Seed sensitivity
1,PD,seed43,4,6,NaN,256,Seed sensitivity
2,PD,one_sample,4,6,NaN,256,Sampling execution
3,PD,full_pass,4,6,NaN,256,Sampling execution
4,PD,accumulate,4,6,NaN,256,Sampling execution
5,PD,full_pass_resumed,4,6,3.0,256,Resume equivalence
6,PD,accumulate_resumed,4,6,3.0,256,Resume equivalence
7,LGD,seed42,4,6,NaN,256,Seed sensitivity
8,LGD,seed43,4,6,NaN,256,Seed sensitivity
9,LGD,full_pass,4,6,NaN,256,Sampling execution
10,LGD,accumulate,4,6,NaN,256,Sampling execution
11,LGD,full_pass_resumed,4,6,3.0,256,Resume equivalence
12,LGD,accumulate_resumed,4,6,3.0,256,Resume equivalence

## 2. Seed and recovery evidence

Seed 43 must change trained weights while preserving fixed update-zero monitors. Each full-pass and accumulation continuation must match its uninterrupted reference in weights, monitor values and row exposure. A failed, absent or pending task is not a pass.

In [3]:
scope, checks, arms = aux.evidence()
print(scope)
report.table('Per-task functional checks', checks)
report.add('2. Seed and recovery evidence', str(scope))

{'status': 'Not run: no downloaded auxiliary workflow evidence.'}

Empty DataFrame
Columns: []
Index: []

## 3. Budget, sampling and evaluation

Full pass updates after each chunk; accumulation averages chunk gradients and updates once per table. Both traverse disjoint rows and repartition next epoch. The reloaded seed-43 checkpoint also undergoes five-fold package-data evaluation with inner-validation threshold or calibration fitting.

In [4]:
report.table('Recorded arms and processed row exposures', arms)
report.add('3. Budget, sampling and evaluation', 'Equal successful-update counts do not imply equal row exposure or GPU cost. Functional success requires all eight task reports and the CPU audit receipt. The workflow never automatically starts a research experiment.')

Empty DataFrame
Columns: []
Index: []

## Complete text summary

In [5]:
print(report.summary(sink))

Experiment 0: auxiliary experiment checks

0. Evidence and scope
DATA: no external source selected.
Project: no external source selected.
Missing project records are unavailable evidence, not zero effects or failed training.

1. Planned checks
52 six-update arms across eight GPU tasks: 36 uninterrupted arms and 16 interrupted/resumed comparisons. LGD seed-42 one-sample also serves as the stratified sampling control. PD has a separate stratified control. The tiny 256-row cap and smoke retention panel bound debugging cost.

Table: Planned auxiliary cases
   track                case  bases  updates  interrupt_after  row_cap             purpose
0     PD              seed42      4        6      unavailable      256    Seed sensitivity
1     PD              seed43      4        6      unavailable      256    Seed sensitivity
2     PD          one_sample      4        6      unavailable      256  Sampling execution
3     PD           full_pass      4        6      unavailable      256  Sampling execution
4     PD          accumulate      4        6      unavailable      256  Sampling execution
5     PD   full_pass_resumed      4        6                3      256  Resume equivalence
6     PD  accumulate_resumed      4        6                3      256  Resume equivalence
7    LGD              seed42      4        6      unavailable      256    Seed sensitivity
8    LGD              seed43      4        6      unavailable      256    Seed sensitivity
9    LGD           full_pass      4        6      unavailable      256  Sampling execution
10   LGD          accumulate      4        6      unavailable      256  Sampling execution
11   LGD   full_pass_resumed      4        6                3      256  Resume equivalence
12   LGD  accumulate_resumed      4        6                3      256  Resume equivalence

2. Seed and recovery evidence
{'status': 'Not run: no downloaded auxiliary workflow evidence.'}

Table: Per-task functional checks
Empty DataFrame
Columns: []
Index: []

3. Budget, sampling and evaluation
Equal successful-update counts do not imply equal row exposure or GPU cost. Functional success requires all eight task reports and the CPU audit receipt. The workflow never automatically starts a research experiment.

Table: Recorded arms and processed row exposures
Empty DataFrame
Columns: []
Index: []

experiment0/04_auxiliary_experiments: no figures saved.