# Experiment 5: DiagScale transfer and retention

Evaluate the three DiagScale rates against their own original checkpoints using five outer folds on excluded credit tables and the fixed non-credit panel. All rates are reported. Original and adapter inference share precision settings. Earlier full-parameter CPT used other precision, episode and sampling settings and is not treated as a one-factor control here.

Can restricting cross-table credit adaptation to query scaling preserve useful in-context behavior? This is fixed-endpoint domain CPT, not target-table validation-selected fine-tuning.

## 0. Evidence and scope

In [1]:
%matplotlib inline
import sys
from pathlib import Path
REPO = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / 'pyproject.toml').is_file())
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))
from src.visualize import style, campaign as cp
from src.visualize.figures import FigureSaver
from src.visualize.inputs import source_description
style.apply()
from src.visualize import adapter_study as ds, publication as pub, comparisons as cmp, dashboards as db
sink = FigureSaver('experiment5/02_results')
report = cp.NotebookReport('Experiment 5: DiagScale transfer and retention', sink=sink)
print(source_description())
report.add('0. Evidence and scope', source_description() + '\n' + 'Can restricting cross-table credit adaptation to query scaling preserve useful in-context behavior? This is fixed-endpoint domain CPT, not target-table validation-selected fine-tuning.')
runs = [cp.load_campaign(5, track) for track in ('pd', 'lgd')]
from src.visualize import prediction_diagnostics as pred

DATA: output CreditPFN.zip; modified 2026-10-16T07:14:04+00:00; read only.
Project: output CreditPFN; modified 2026-10-16T08:49:22+00:00; read only.
Missing project records are unavailable evidence, not zero effects or failed training.

## 1. Checkpoint and benchmark coverage

In [2]:
for run in runs:
    report.table(run.track.upper()+' evidence', pub.availability(run))
    report.table(run.track.upper()+' paired benchmark coverage', cmp.benchmark_coverage(run))
report.add('1. Checkpoint and benchmark coverage', 'Trained and original cells need all five finite outer folds. Non-credit table comparisons additionally require all four training-dataset partitions. Missing cells remain unavailable.')

           evidence  records                          origin
0    Planned trials       24     Config; not scheduler state
1  Completed trials       24                  DATA manifests
2        Epoch rows    18888    Project training diagnostics
3    Milestone rows      144  Project trajectory diagnostics
4   Benchmark folds        0        Project final evaluation

,domain,base,planned_checkpoints,completed_checkpoints,paired_five_fold_comparisons,paired_datasets
0,credit,TabICLv2,12,12,0,0
1,credit,TabPFN v3,12,12,0,0
2,ood,TabICLv2,12,12,0,0
3,ood,TabPFN v3,12,12,0,0

           evidence  records                          origin
0    Planned trials       24     Config; not scheduler state
1  Completed trials       24                  DATA manifests
2        Epoch rows    15012    Project training diagnostics
3    Milestone rows       54  Project trajectory diagnostics
4   Benchmark folds        0        Project final evaluation

,domain,base,planned_checkpoints,completed_checkpoints,paired_five_fold_comparisons,paired_datasets
0,credit,TabICLv2,12,12,0,0
1,credit,TabPFN v3,12,12,0,0
2,ood,TabICLv2,12,12,0,0
3,ood,TabPFN v3,12,12,0,0

## 2. Five-fold credit transfer and non-credit retention

Points show tables; diamonds show their mean and intervals their interquartile range. All three rates share a table cohort within each model/domain panel. PD uses AUC and LGD uses R².

In [3]:
for run in runs:
    cp.show(sink, ds.plot_benchmark(run))
    for domain in ('credit', 'ood'):
        report.table(run.track.upper()+' '+domain+' paired primary scores', ds.benchmark_tables(run, domain=domain))
    report.table(run.track.upper()+' absolute scores including available classical controls', ds.absolute_scores(run))
report.add('2. Five-fold credit transfer and non-credit retention', 'Positive effects favor DiagScale. Table spread is not a confidence interval. The highest observed rate is not a validated selected recipe. Classical models provide benchmark context rather than a checkpoint-paired causal contrast.')

No measurements available for this section yet.

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

No measurements available for this section yet.

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

## 3. Probability quality and regression errors

Saved raw test predictions additionally measure systematic over/underprediction and paired prediction changes. These diagnostics describe observed errors; they do not identify theoretical bias or context variance.

In [4]:
for run in runs:
    if run.track == 'pd':
        cp.show(sink, ds.plot_benchmark(run, metric='brier_score'))
    for metric in (('brier_score', 'log_loss', 'ece', 'f1') if run.track == 'pd' else ('rmse', 'mae')):
        for domain in ('credit', 'ood'):
            report.table(run.track.upper()+' '+domain+' '+metric, ds.benchmark_tables(run, metric, domain))
for run in runs:
    prediction_values, prediction_coverage = pred.analyze(run)
    report.table(run.track.upper()+' saved prediction coverage', prediction_coverage)
    report.table(run.track.upper()+' paired per-table prediction diagnostics', prediction_values)
    cp.show(sink, pred.plot_diagnostics(prediction_values, run.track, coverage=prediction_coverage))
report.add('3. Probability quality and regression errors', 'Probabilities are evaluated at test prevalence. F1/calibration rules use inner validation only. RMSE effects are fractional reductions relative to the matched original; other differences retain their metric scale. Unsupported/nonfinite metrics are not filled with zeros.' + '\n' + pred.NOTE)

No measurements available for this section yet.

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

        status                reason
0  unavailable  No benchmark records

Empty DataFrame
Columns: []
Index: []

No measurements available for this section yet.

        status                reason
0  unavailable  No benchmark records

Empty DataFrame
Columns: []
Index: []

No measurements available for this section yet.

## 4. Cost and interpretation boundaries

In [5]:
for run in runs:
    report.table(run.track.upper()+' training resources', ds.costs(run))
report.add('4. Cost and interpretation boundaries', 'This experiment tests a cross-table DiagScale recipe. It is not a literal reproduction of target-table adapter fine-tuning, nor a pure parameter-count ablation against previous full-update runs. Overlapping training corpora, related data sources and the small retention panel limit independence and generality claims. Report unfavorable outcomes alongside improvements.')

,trial_name,base,learning_rate,partition,status,optimizer_selected_params,total_params,rows_seen,elapsed_sec,gpu_hours,peak_gpu_gb,query_scale_delta_rms
0,cpt_diagscale_v1_s00_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0001,0,OK,13056,53166200,70788725,6168.156499,1.713377,39.133,0.032038
1,cpt_diagscale_v1_s00_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0010,0,OK,13056,53166200,70788725,6147.738720,1.707705,39.345,0.184803
2,cpt_diagscale_v1_s00_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0300,0,OK,13056,53166200,70788725,6169.156107,1.713654,39.133,1.263868
3,cpt_diagscale_v1_s00_pd_tabicl-classifier-v2-2...,TabICLv2,0.0001,0,OK,7296,27559554,70788725,4766.576668,1.324049,15.873,0.038982
4,cpt_diagscale_v1_s00_pd_tabicl-classifier-v2-2...,TabICLv2,0.0010,0,OK,7296,27559554,70788725,4770.898052,1.325249,15.873,0.275439
5,cpt_diagscale_v1_s00_pd_tabicl-classifier-v2-2...,TabICLv2,0.0300,0,OK,7296,27559554,70788725,4776.914145,1.326921,15.763,1.640877
6,cpt_diagscale_v1_s01_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0001,1,OK,13056,53166200,69239144,6049.478816,1.680411,39.771,0.033577
7,cpt_diagscale_v1_s01_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0010,1,OK,13056,53166200,69239144,6071.310221,1.686475,39.558,0.199136
8,cpt_diagscale_v1_s01_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0300,1,OK,13056,53166200,69239144,6096.050658,1.693347,39.771,1.233613
9,cpt_diagscale_v1_s01_pd_tabicl-classifier-v2-2...,TabICLv2,0.0001,1,OK,7296,27559554,69239144,4809.640543,1.336011,15.873,0.053894
10,cpt_diagscale_v1_s01_pd_tabicl-classifier-v2-2...,TabICLv2,0.0010,1,OK,7296,27559554,69239144,4774.199204,1.326166,15.873,0.260583
11,cpt_diagscale_v1_s01_pd_tabicl-classifier-v2-2...,TabICLv2,0.0300,1,OK,7296,27559554,69239144,4787.368036,1.329824,15.873,1.552805
12,cpt_diagscale_v1_s02_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0001,2,OK,13056,53166200,63185527,5537.935838,1.538316,39.558,0.038331
13,cpt_diagscale_v1_s02_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0010,2,OK,13056,53166200,63185527,5527.959630,1.535544,39.558,0.230977
14,cpt_diagscale_v1_s02_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0300,2,OK,13056,53166200,63185527,5549.815119,1.541615,39.558,1.497658
15,cpt_diagscale_v1_s02_pd_tabicl-classifier-v2-2...,TabICLv2,0.0001,2,OK,7296,27559554,63185527,4302.750847,1.195209,15.873,0.052741
16,cpt_diagscale_v1_s02_pd_tabicl-classifier-v2-2...,TabICLv2,0.0010,2,OK,7296,27559554,63185527,4293.889484,1.192747,15.763,0.289766
17,cpt_diagscale_v1_s02_pd_tabicl-classifier-v2-2...,TabICLv2,0.0300,2,OK,7296,27559554,63185527,4290.198360,1.191722,15.763,1.878218
18,cpt_diagscale_v1_s03_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0001,3,OK,13056,53166200,68390711,5798.294845,1.610637,39.345,0.033328
19,cpt_diagscale_v1_s03_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0010,3,OK,13056,53166200,68390711,5756.081072,1.598911,39.345,0.190676
20,cpt_diagscale_v1_s03_pd_tabpfn-v3-classifier-v...,TabPFN v3,0.0300,3,OK,13056,53166200,68390711,5747.647367,1.596569,39.345,1.144153
21,cpt_diagscale_v1_s03_pd_tabicl-classifier-v2-2...,TabICLv2,0.0001,3,OK,7296,27559554,68390711,4427.402064,1.229834,15.763,0.054245
22,cpt_diagscale_v1_s03_pd_tabicl-classifier-v2-2...,TabICLv2,0.0010,3,OK,7296,27559554,68390711,4409.103552,1.224751,15.763,0.269849
23,cpt_diagscale_v1_s03_pd_tabicl-classifier-v2-2...,TabICLv2,0.0300,3,OK,7296,27559554,68390711,4404.543859,1.223484,15.763,1.683888

,trial_name,base,learning_rate,partition,status,optimizer_selected_params,total_params,rows_seen,elapsed_sec,gpu_hours,peak_gpu_gb,query_scale_delta_rms
0,cpt_diagscale_v1_s00_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0001,0,OK,12672,58287616,40087565,3079.852087,0.855514,23.140,0.080004
1,cpt_diagscale_v1_s00_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0010,0,OK,12672,58287616,40087565,3075.246109,0.854235,23.140,0.373031
2,cpt_diagscale_v1_s00_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0300,0,OK,12672,58287616,40087565,3096.738649,0.860205,23.140,2.073015
3,cpt_diagscale_v1_s00_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0001,0,OK,7296,28552287,40087565,2277.811915,0.632726,6.741,0.056318
4,cpt_diagscale_v1_s00_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0010,0,OK,7296,28552287,40087565,2279.549649,0.633208,6.741,0.354603
5,cpt_diagscale_v1_s00_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0300,0,OK,7296,28552287,40087565,2282.008839,0.633891,6.627,2.086672
6,cpt_diagscale_v1_s01_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0001,1,OK,12672,58287616,24755261,1964.853834,0.545793,21.967,0.083976
7,cpt_diagscale_v1_s01_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0010,1,OK,12672,58287616,24755261,1969.742728,0.547151,21.967,0.398106
8,cpt_diagscale_v1_s01_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0300,1,OK,12672,58287616,24755261,1951.440194,0.542067,21.967,2.063494
9,cpt_diagscale_v1_s01_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0001,1,OK,7296,28552287,24755261,1577.989593,0.438330,6.838,0.053744
10,cpt_diagscale_v1_s01_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0010,1,OK,7296,28552287,24755261,1567.363870,0.435379,6.838,0.351763
11,cpt_diagscale_v1_s01_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0300,1,OK,7296,28552287,24755261,1563.930811,0.434425,6.838,1.939571
12,cpt_diagscale_v1_s02_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0001,2,OK,12672,58287616,41695031,3230.934071,0.897482,23.140,0.084769
13,cpt_diagscale_v1_s02_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0010,2,OK,12672,58287616,41695031,3244.964325,0.901379,23.373,0.392038
14,cpt_diagscale_v1_s02_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0300,2,OK,12672,58287616,41695031,3213.848223,0.892736,23.373,2.028394
15,cpt_diagscale_v1_s02_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0001,2,OK,7296,28552287,41695031,2410.745159,0.669651,6.838,0.060955
16,cpt_diagscale_v1_s02_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0010,2,OK,7296,28552287,41695031,2406.995235,0.668610,6.838,0.355380
17,cpt_diagscale_v1_s02_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0300,2,OK,7296,28552287,41695031,2413.326060,0.670368,6.838,2.052335
18,cpt_diagscale_v1_s03_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0001,3,OK,12672,58287616,49651790,3696.154398,1.026710,23.140,0.096689
19,cpt_diagscale_v1_s03_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0010,3,OK,12672,58287616,49651790,3695.573698,1.026548,23.140,0.426263
20,cpt_diagscale_v1_s03_lgd_tabpfn-v3-regressor-v...,TabPFN v3,0.0300,3,OK,12672,58287616,49651790,3710.076702,1.030577,23.140,2.168302
21,cpt_diagscale_v1_s03_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0001,3,OK,7296,28552287,49651790,2739.176662,0.760882,6.838,0.056821
22,cpt_diagscale_v1_s03_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0010,3,OK,7296,28552287,49651790,2754.511934,0.765142,6.838,0.334767
23,cpt_diagscale_v1_s03_lgd_tabicl-regressor-v2-2...,TabICLv2,0.0300,3,OK,7296,28552287,49651790,2745.990806,0.762775,6.838,1.781827

## Complete text summary

All displayed numerical values and captions, in section order.

In [6]:
print(report.summary(sink))

Experiment 5: DiagScale transfer and retention

0. Evidence and scope
DATA: output CreditPFN.zip; modified 2026-10-16T07:14:04+00:00; read only.
Project: output CreditPFN; modified 2026-10-16T08:49:22+00:00; read only.
Missing project records are unavailable evidence, not zero effects or failed training.
Can restricting cross-table credit adaptation to query scaling preserve useful in-context behavior? This is fixed-endpoint domain CPT, not target-table validation-selected fine-tuning.

1. Checkpoint and benchmark coverage
Trained and original cells need all five finite outer folds. Non-credit table comparisons additionally require all four training-dataset partitions. Missing cells remain unavailable.

Table: PD evidence
CSV (first column: row index)
row,evidence,records,origin
0,Planned trials,24,Config; not scheduler state
1,Completed trials,24,DATA manifests
2,Epoch rows,18888,Project training diagnostics
3,Milestone rows,144,Project trajectory diagnostics
4,Benchmark folds,0,Project final evaluation

Table: PD paired benchmark coverage
CSV (first column: row index)
row,domain,base,planned_checkpoints,completed_checkpoints,paired_five_fold_comparisons,paired_datasets
0,credit,TabICLv2,12,12,0,0
1,credit,TabPFN v3,12,12,0,0
2,ood,TabICLv2,12,12,0,0
3,ood,TabPFN v3,12,12,0,0

Table: LGD evidence
CSV (first column: row index)
row,evidence,records,origin
0,Planned trials,24,Config; not scheduler state
1,Completed trials,24,DATA manifests
2,Epoch rows,15012,Project training diagnostics
3,Milestone rows,54,Project trajectory diagnostics
4,Benchmark folds,0,Project final evaluation

Table: LGD paired benchmark coverage
CSV (first column: row index)
row,domain,base,planned_checkpoints,completed_checkpoints,paired_five_fold_comparisons,paired_datasets
0,credit,TabICLv2,12,12,0,0
1,credit,TabPFN v3,12,12,0,0
2,ood,TabICLv2,12,12,0,0
3,ood,TabPFN v3,12,12,0,0

2. Five-fold credit transfer and non-credit retention
Positive effects favor DiagScale. Table spread is not a confidence interval. The highest observed rate is not a validated selected recipe. Classical models provide benchmark context rather than a checkpoint-paired causal contrast.

No measurements available for this figure group.

Table: PD credit paired primary scores
CSV (first column: row index)
row

Table: PD ood paired primary scores
CSV (first column: row index)
row

Table: PD absolute scores including available classical controls
CSV (first column: row index)
row

No measurements available for this figure group.

Table: LGD credit paired primary scores
CSV (first column: row index)
row

Table: LGD ood paired primary scores
CSV (first column: row index)
row

Table: LGD absolute scores including available classical controls
CSV (first column: row index)
row

3. Probability quality and regression errors
Probabilities are evaluated at test prevalence. F1/calibration rules use inner validation only. RMSE effects are fractional reductions relative to the matched original; other differences retain their metric scale. Unsupported/nonfinite metrics are not filled with zeros.
Raw predictions are paired by dataset, training partition, outer fold and row. All five folds and exactly matching test rows/targets are required. Mean error is prediction minus observed target: positive means overprediction. Its absolute value can conceal offsetting subgroup errors. Brier/MSE and prediction movement pool rows within each table; tables receive equal weight in summaries. These are observed out-of-fold diagnostics, not squared theoretical bias or context variance.

No measurements available for this figure group.

Table: PD credit brier_score
CSV (first column: row index)
row

Table: PD ood brier_score
CSV (first column: row index)
row

Table: PD credit log_loss
CSV (first column: row index)
row

Table: PD ood log_loss
CSV (first column: row index)
row

Table: PD credit ece
CSV (first column: row index)
row

Table: PD ood ece
CSV (first column: row index)
row

Table: PD credit f1
CSV (first column: row index)
row

Table: PD ood f1
CSV (first column: row index)
row

Table: LGD credit rmse
CSV (first column: row index)
row

Table: LGD ood rmse
CSV (first column: row index)
row

Table: LGD credit mae
CSV (first column: row index)
row

Table: LGD ood mae
CSV (first column: row index)
row

Table: PD saved prediction coverage
CSV (first column: row index)
row,status,reason
0,unavailable,No benchmark records

Table: PD paired per-table prediction diagnostics
CSV (first column: row index)
row

No measurements available for this figure group.

Table: LGD saved prediction coverage
CSV (first column: row index)
row,status,reason
0,unavailable,No benchmark records

Table: LGD paired per-table prediction diagnostics
CSV (first column: row index)
row

No measurements available for this figure group.

4. Cost and interpretation boundaries
This experiment tests a cross-table DiagScale recipe. It is not a literal reproduction of target-table adapter fine-tuning, nor a pure parameter-count ablation against previous full-update runs. Overlapping training corpora, related data sources and the small retention panel limit independence and generality claims. Report unfavorable outcomes alongside improvements.

Table: PD training resources
CSV (first column: row index)
row,trial_name,base,learning_rate,partition,status,optimizer_selected_params,total_params,rows_seen,elapsed_sec,gpu_hours,peak_gpu_gb,query_scale_delta_rms
0,cpt_diagscale_v1_s00_pd_tabpfn-v3-classifier-v3_default_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.0001,0,OK,13056,53166200,70788725,6168.1565,1.7133768,39.133,0.032037512
1,cpt_diagscale_v1_s00_pd_tabpfn-v3-classifier-v3_default_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.001,0,OK,13056,53166200,70788725,6147.7387,1.7077052,39.345,0.18480313
2,cpt_diagscale_v1_s00_pd_tabpfn-v3-classifier-v3_default_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.03,0,OK,13056,53166200,70788725,6169.1561,1.7136545,39.133,1.2638681
3,cpt_diagscale_v1_s00_pd_tabicl-classifier-v2-20260212_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.0001,0,OK,7296,27559554,70788725,4766.5767,1.3240491,15.873,0.038982435
4,cpt_diagscale_v1_s00_pd_tabicl-classifier-v2-20260212_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.001,0,OK,7296,27559554,70788725,4770.8981,1.3252495,15.873,0.27543875
5,cpt_diagscale_v1_s00_pd_tabicl-classifier-v2-20260212_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.03,0,OK,7296,27559554,70788725,4776.9141,1.3269206,15.763,1.6408769
6,cpt_diagscale_v1_s01_pd_tabpfn-v3-classifier-v3_default_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.0001,1,OK,13056,53166200,69239144,6049.4788,1.6804108,39.771,0.033577253
7,cpt_diagscale_v1_s01_pd_tabpfn-v3-classifier-v3_default_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.001,1,OK,13056,53166200,69239144,6071.3102,1.6864751,39.558,0.19913632
8,cpt_diagscale_v1_s01_pd_tabpfn-v3-classifier-v3_default_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.03,1,OK,13056,53166200,69239144,6096.0507,1.6933474,39.771,1.2336133
9,cpt_diagscale_v1_s01_pd_tabicl-classifier-v2-20260212_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.0001,1,OK,7296,27559554,69239144,4809.6405,1.3360113,15.873,0.053893509
10,cpt_diagscale_v1_s01_pd_tabicl-classifier-v2-20260212_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.001,1,OK,7296,27559554,69239144,4774.1992,1.3261664,15.873,0.26058342
11,cpt_diagscale_v1_s01_pd_tabicl-classifier-v2-20260212_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.03,1,OK,7296,27559554,69239144,4787.368,1.3298245,15.873,1.5528046
12,cpt_diagscale_v1_s02_pd_tabpfn-v3-classifier-v3_default_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.0001,2,OK,13056,53166200,63185527,5537.9358,1.5383155,39.558,0.038330981
13,cpt_diagscale_v1_s02_pd_tabpfn-v3-classifier-v3_default_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.001,2,OK,13056,53166200,63185527,5527.9596,1.5355443,39.558,0.23097673
14,cpt_diagscale_v1_s02_pd_tabpfn-v3-classifier-v3_default_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.03,2,OK,13056,53166200,63185527,5549.8151,1.5416153,39.558,1.497658
15,cpt_diagscale_v1_s02_pd_tabicl-classifier-v2-20260212_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.0001,2,OK,7296,27559554,63185527,4302.7508,1.1952086,15.873,0.052740983
16,cpt_diagscale_v1_s02_pd_tabicl-classifier-v2-20260212_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.001,2,OK,7296,27559554,63185527,4293.8895,1.1927471,15.763,0.28976627
17,cpt_diagscale_v1_s02_pd_tabicl-classifier-v2-20260212_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.03,2,OK,7296,27559554,63185527,4290.1984,1.1917218,15.763,1.8782183
18,cpt_diagscale_v1_s03_pd_tabpfn-v3-classifier-v3_default_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.0001,3,OK,13056,53166200,68390711,5798.2948,1.6106375,39.345,0.03332759
19,cpt_diagscale_v1_s03_pd_tabpfn-v3-classifier-v3_default_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.001,3,OK,13056,53166200,68390711,5756.0811,1.5989114,39.345,0.19067555
20,cpt_diagscale_v1_s03_pd_tabpfn-v3-classifier-v3_default_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.03,3,OK,13056,53166200,68390711,5747.6474,1.5965687,39.345,1.1441528
21,cpt_diagscale_v1_s03_pd_tabicl-classifier-v2-20260212_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.0001,3,OK,7296,27559554,68390711,4427.4021,1.2298339,15.763,0.054244559
22,cpt_diagscale_v1_s03_pd_tabicl-classifier-v2-20260212_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.001,3,OK,7296,27559554,68390711,4409.1036,1.224751,15.763,0.2698493
23,cpt_diagscale_v1_s03_pd_tabicl-classifier-v2-20260212_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.03,3,OK,7296,27559554,68390711,4404.5439,1.2234844,15.763,1.6838884

Table: LGD training resources
CSV (first column: row index)
row,trial_name,base,learning_rate,partition,status,optimizer_selected_params,total_params,rows_seen,elapsed_sec,gpu_hours,peak_gpu_gb,query_scale_delta_rms
0,cpt_diagscale_v1_s00_lgd_tabpfn-v3-regressor-v3_default_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.0001,0,OK,12672,58287616,40087565,3079.8521,0.85551447,23.14,0.080004288
1,cpt_diagscale_v1_s00_lgd_tabpfn-v3-regressor-v3_default_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.001,0,OK,12672,58287616,40087565,3075.2461,0.85423503,23.14,0.3730311
2,cpt_diagscale_v1_s00_lgd_tabpfn-v3-regressor-v3_default_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.03,0,OK,12672,58287616,40087565,3096.7386,0.86020518,23.14,2.0730148
3,cpt_diagscale_v1_s00_lgd_tabicl-regressor-v2-20260212_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.0001,0,OK,7296,28552287,40087565,2277.8119,0.63272553,6.741,0.056317653
4,cpt_diagscale_v1_s00_lgd_tabicl-regressor-v2-20260212_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.001,0,OK,7296,28552287,40087565,2279.5496,0.63320824,6.741,0.35460257
5,cpt_diagscale_v1_s00_lgd_tabicl-regressor-v2-20260212_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.03,0,OK,7296,28552287,40087565,2282.0088,0.63389134,6.627,2.0866718
6,cpt_diagscale_v1_s01_lgd_tabpfn-v3-regressor-v3_default_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.0001,1,OK,12672,58287616,24755261,1964.8538,0.54579273,21.967,0.083976417
7,cpt_diagscale_v1_s01_lgd_tabpfn-v3-regressor-v3_default_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.001,1,OK,12672,58287616,24755261,1969.7427,0.54715076,21.967,0.3981064
8,cpt_diagscale_v1_s01_lgd_tabpfn-v3-regressor-v3_default_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.03,1,OK,12672,58287616,24755261,1951.4402,0.54206672,21.967,2.0634938
9,cpt_diagscale_v1_s01_lgd_tabicl-regressor-v2-20260212_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.0001,1,OK,7296,28552287,24755261,1577.9896,0.43833044,6.838,0.053744063
10,cpt_diagscale_v1_s01_lgd_tabicl-regressor-v2-20260212_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.001,1,OK,7296,28552287,24755261,1567.3639,0.43537885,6.838,0.35176272
11,cpt_diagscale_v1_s01_lgd_tabicl-regressor-v2-20260212_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.03,1,OK,7296,28552287,24755261,1563.9308,0.43442523,6.838,1.9395714
12,cpt_diagscale_v1_s02_lgd_tabpfn-v3-regressor-v3_default_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.0001,2,OK,12672,58287616,41695031,3230.9341,0.89748169,23.14,0.084768721
13,cpt_diagscale_v1_s02_lgd_tabpfn-v3-regressor-v3_default_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.001,2,OK,12672,58287616,41695031,3244.9643,0.90137898,23.373,0.39203815
14,cpt_diagscale_v1_s02_lgd_tabpfn-v3-regressor-v3_default_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.03,2,OK,12672,58287616,41695031,3213.8482,0.89273562,23.373,2.0283941
15,cpt_diagscale_v1_s02_lgd_tabicl-regressor-v2-20260212_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.0001,2,OK,7296,28552287,41695031,2410.7452,0.66965143,6.838,0.060955019
16,cpt_diagscale_v1_s02_lgd_tabicl-regressor-v2-20260212_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.001,2,OK,7296,28552287,41695031,2406.9952,0.66860979,6.838,0.35537952
17,cpt_diagscale_v1_s02_lgd_tabicl-regressor-v2-20260212_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.03,2,OK,7296,28552287,41695031,2413.3261,0.67036835,6.838,2.0523347
18,cpt_diagscale_v1_s03_lgd_tabpfn-v3-regressor-v3_default_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.0001,3,OK,12672,58287616,49651790,3696.1544,1.0267096,23.14,0.096689395
19,cpt_diagscale_v1_s03_lgd_tabpfn-v3-regressor-v3_default_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.001,3,OK,12672,58287616,49651790,3695.5737,1.0265482,23.14,0.42626287
20,cpt_diagscale_v1_s03_lgd_tabpfn-v3-regressor-v3_default_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabPFN v3,0.03,3,OK,12672,58287616,49651790,3710.0767,1.0305769,23.14,2.1683015
21,cpt_diagscale_v1_s03_lgd_tabicl-regressor-v2-20260212_lr1e-04_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.0001,3,OK,7296,28552287,49651790,2739.1767,0.76088241,6.838,0.056821324
22,cpt_diagscale_v1_s03_lgd_tabicl-regressor-v2-20260212_lr1e-03_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.001,3,OK,7296,28552287,49651790,2754.5119,0.7651422,6.838,0.33476712
23,cpt_diagscale_v1_s03_lgd_tabicl-regressor-v2-20260212_lr3e-02_seed42_qf40_acc1_l2sp0_diagscale,TabICLv2,0.03,3,OK,7296,28552287,49651790,2745.9908,0.76277522,6.838,1.7818273

experiment5/02_results: no figures saved.