# Experiment 4: labeled context and the value of CPT

Compare original TabPFN v3 and TabICLv2 with a fixed continued-pretraining (CPT) recipe as labeled context shrinks. Each target table was excluded from its CPT checkpoint. No weights are fitted here. Five outer folds cover all test rows; a separate, fixed validation-label budget supports threshold and calibration rules. This is a context-memory curve, not a curve for the total number of labels acquired.

## 0. Evidence and scope

In [1]:
%matplotlib inline
import sys
from pathlib import Path
REPO = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / 'pyproject.toml').is_file())
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))
from src.visualize import style, campaign as cp
from src.visualize.figures import FigureSaver
from src.visualize.inputs import source_description
style.apply()
from src.visualize import context_curves as cc
sink = FigureSaver('experiment4/01_context_curves')
report = cp.NotebookReport('Experiment 4: labeled context and the value of CPT', sink=sink)
print(source_description())
report.add('0. Evidence and scope', source_description())
study = cc.load_context_study()

DATA: output CreditPFN.zip; modified 2026-10-13T12:13:29+00:00; read only.
Project: output CreditPFN; modified 2026-10-13T13:56:42+00:00; read only.
Missing project records are unavailable evidence, not zero effects or failed training.

## 1. Fixed checkpoints and evaluation protocol

The CPT reference is the predefined full-parameter experiment-1 recipe, not the best result observed in the sweep. Context prefixes are nested and shared between original and CPT models. Inference views stay fixed within each family.

In [2]:
report.table('Evaluation protocol', cc.protocol_table(study))
report.add('1. Fixed checkpoints and evaluation protocol', 'The 50,000-row cap bounds computation; it is not TabPFN v3’s native limit. The available-pool endpoint is included when distinct. Validation and test rows never enter context.')

               setting                                              value
0               Models  Explicit TabPFN v3 and TabICLv2 original/CPT p...
1           CPT source  cpt_main_v5; full updates; LR 3e-07; L2-SP 0.0...
2    Dataset exclusion  Each table uses its original experiment-1 held...
3     Outer test folds                                                  5
4         Context rows  8, 12, 16, 24, 32, 48, 64, 96, 128, 192, 256, ...
5  Additional endpoint  Available context pool, capped at 50,000, with...
6    Validation labels  Fixed 20% of each outer training fold, separat...
7            Test rows  All outer-test rows; unchanged across context ...
8      Inference views                        {'tabpfn': 32, 'tabicl': 8}
9          Aggregation  Five paired folds per table; equal-weight tabl...

## 2. Completed exports and five-fold support

A completed task supplies one table, model family and outer fold. Its compressed metric export must match the prepared plan and completion receipt. Partially written SQLite journals are recovery evidence and are not counted as completed metric exports.

In [3]:
report.table('Task inventory', study.inventory)
cp.show(sink, cc.plot_context_support(study))
report.add('2. Completed exports and five-fold support', 'Absent exports are unavailable evidence, not zero performance. DATA plans/receipts and project metric exports are both needed. Coverage counts are not live scheduler status.')

             status  tasks  exports  journals
0  Plan unavailable      0        0         0

No measurements available for this section yet.

## 3. Original and CPT context curves

Separate panels cover context horizons of 128, 2,048 and 50,000 rows. Within each horizon, the same tables must support every displayed context size and both model families. The fixed cohorts prevent changes in table mix from looking like gains from more context. Different horizons can therefore have different table cohorts.

In [4]:
cp.show(sink, cc.plot_context_curves(study))
report.add('3. Original and CPT context curves', 'Primary scores are PD AUC and LGD R². Scores first average the five paired folds within each table, then weight tables equally. Positive differences favor CPT. No figure is generated for a horizon without a complete common cohort.')

No measurements available for this section yet.

## 4. Calibration, errors and inference cost

Retain paired table-level values at every measured context size, including available-pool endpoints. These tables include proper scoring rules, validation-selected F1 and elapsed inference time; their distinct units are preserved.

In [5]:
for metric, table in cc.secondary_tables(study).items():
    report.table(metric+' paired table values', table)
report.add('4. Calibration, errors and inference cost', 'Brier score, log loss, ECE, RMSE, MAE and elapsed-time gains use original minus CPT; AUC, R² and F1 gains use CPT minus original. Timing includes fitting and validation/test prediction, excludes prior CPT training and queue time, and can be affected by fixed execution order. Fold averages are descriptive, not independent table replications.')

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

## Complete text summary

All displayed numerical values and captions, in section order.

In [6]:
print(report.summary(sink))

Experiment 4: labeled context and the value of CPT

0. Evidence and scope
DATA: output CreditPFN.zip; modified 2026-10-13T12:13:29+00:00; read only.
Project: output CreditPFN; modified 2026-10-13T13:56:42+00:00; read only.
Missing project records are unavailable evidence, not zero effects or failed training.

1. Fixed checkpoints and evaluation protocol
The 50,000-row cap bounds computation; it is not TabPFN v3’s native limit. The available-pool endpoint is included when distinct. Validation and test rows never enter context.

Table: Evaluation protocol
CSV (first column: row index)
row,setting,value
0,Models,Explicit TabPFN v3 and TabICLv2 original/CPT pairs
1,CPT source,cpt_main_v5; full updates; LR 3e-07; L2-SP 0.003; seed 42; 10000 updates
2,Dataset exclusion,Each table uses its original experiment-1 held-out partition's checkpoint
3,Outer test folds,5
4,Context rows,"8, 12, 16, 24, 32, 48, 64, 96, 128, 192, 256, 384, 512, 768, 1024, 1536, 2048, 3072, 4096, 6144, 8192, 12288, 16384, 20480, 24576, 32768, 40960, 49152, 50000"
5,Additional endpoint,"Available context pool, capped at 50,000, without duplicate sizes"
6,Validation labels,"Fixed 20% of each outer training fold, separate from context"
7,Test rows,All outer-test rows; unchanged across context budgets and original/CPT
8,Inference views,"{'tabpfn': 32, 'tabicl': 8}"
9,Aggregation,Five paired folds per table; equal-weight table means; fixed cohort within each curve

2. Completed exports and five-fold support
Absent exports are unavailable evidence, not zero performance. DATA plans/receipts and project metric exports are both needed. Coverage counts are not live scheduler status.

Table: Task inventory
CSV (first column: row index)
row,status,tasks,exports,journals
0,Plan unavailable,0,0,0

No measurements available for this figure group.

3. Original and CPT context curves
Primary scores are PD AUC and LGD R². Scores first average the five paired folds within each table, then weight tables equally. Positive differences favor CPT. No figure is generated for a horizon without a complete common cohort.

No measurements available for this figure group.

4. Calibration, errors and inference cost
Brier score, log loss, ECE, RMSE, MAE and elapsed-time gains use original minus CPT; AUC, R² and F1 gains use CPT minus original. Timing includes fitting and validation/test prediction, excludes prior CPT training and queue time, and can be affected by fixed execution order. Fold averages are descriptive, not independent table replications.

Table: roc_auc paired table values
CSV (first column: row index)
row

Table: r2 paired table values
CSV (first column: row index)
row

Table: brier_score paired table values
CSV (first column: row index)
row

Table: log_loss paired table values
CSV (first column: row index)
row

Table: ece paired table values
CSV (first column: row index)
row

Table: f1 paired table values
CSV (first column: row index)
row

Table: rmse paired table values
CSV (first column: row index)
row

Table: mae paired table values
CSV (first column: row index)
row

Table: elapsed_seconds paired table values
CSV (first column: row index)
row

Table: fit_seconds paired table values
CSV (first column: row index)
row

experiment4/01_context_curves: no figures saved.